#!/sbin/busybox sh
#
# Script sysrw by javilonas
#

SYSTEM_DEVICE="/dev/block/mmcblk0p9"

/sbin/busybox mount -o remount,rw -t ext4 $SYSTEM_DEVICE /system
/sbin/busybox mount -t rootfs -o remount,rw rootfs
